### PR TITLE
fixed wordwrap in matches screen

### PR DESCRIPTION
**Pull request by taltaub22**

### CODE REVIEW

**Comment by idanstark42** [comment]
Can you explain the change? How did you fix it and why?

**Comment by taltaub22** [comment]
@idanstark42 wheb there are long tables names the names just going off screen
So I removed the `one line` class and enlarged the header

**Comment by alanggreen** [comment]
@taltaub22 How will this fix solve the issue described in https://trello.com/c/yz2evSwt/429-tournament-matches-list-of-tables-needs-to-wrap

**Comment by taltaub22** [comment]
@alanggreen this is what happens here.
Every column heading is wraped seperately

**Comment by idanstark42** [comment]
@taltaub22 I understand now. Why the left align?

**Comment by taltaub22** [comment]
@idanstark so the header text will be aligned like the data text

**Comment by idanstark42** [comment]
This was aligned center by design, but if you think it looks better then it's ok

**Pull request merged**
